# Generated by Django 6.0.5 on 2026-05-15 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuKopi',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('nama_menu', models.CharField(max_length=100)),
                ('kemanisan', models.IntegerField(help_text='Skala 1-5')),
                ('kepahitan', models.IntegerField(help_text='Skala 1-5')),
                ('keasaman', models.IntegerField(help_text='Skala 1-5')),
                ('body', models.IntegerField(help_text='Skala 1-5')),
                ('aroma', models.IntegerField(help_text='Skala 1-3')),
                ('susu', models.BooleanField(default=False, help_text='0/1')),
                ('suhu', models.BooleanField(default=True, help_text='0=dingin, 1=panas')),
                ('jenis', models.IntegerField(help_text='Kategori')),
                ('kafein', models.IntegerField(help_text='Level')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='coffee_images/')),
            ],
            options={
                'verbose_name': 'Menu Kopi',
                'verbose_name_plural': 'Menu Kopi',
                'db_table': 'menu_kopi',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Preferensi',
            fields=[
                ('id_preferensi', models.AutoField(primary_key=True, serialize=False)),
                ('kemanisan', models.IntegerField()),
                ('kepahitan', models.IntegerField()),
                ('keasaman', models.IntegerField()),
                ('body', models.IntegerField()),
                ('aroma', models.IntegerField()),
                ('susu', models.BooleanField()),
                ('suhu', models.BooleanField()),
                ('jenis_kopi', models.IntegerField()),
                ('kafein', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferensi',
                'verbose_name_plural': 'Preferensi',
                'db_table': 'preferensi',
            },
        ),
        migrations.CreateModel(
            name='Rekomendasi',
            fields=[
                ('id_rekomendasi', models.AutoField(primary_key=True, serialize=False)),
                ('nilai_jarak', models.FloatField()),
                ('ranking', models.IntegerField()),
                ('id_menu', models.ForeignKey(db_column='id_menu', on_delete=django.db.models.deletion.CASCADE, to='recommendation.menukopi')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rekomendasi',
                'verbose_name_plural': 'Rekomendasi',
                'db_table': 'rekomendasi',
            },
        ),
    ]
